services:
  postgres:
    image: postgres:16
    container_name: booking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: court_booking4
    ports:
      - "5433:5432"
    volumes:
      - booking_postgres_data:/var/lib/postgresql/data

volumes:
  booking_postgres_data:
